export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const EXPAND_INSTRUCTIONS = 'EXPAND_INSTRUCTIONS';
export const SET_PLAYER_CHOICE = 'SET_PLAYER_CHOICE';
export const DECK = {
    FETCH_RESULT: 'DECK_FETCH_RESULT',
    FETCH_ERROR: 'DECK_FETCH_ERROR'
};
export const CARD = {
    FETCH_RESULT: 'CARD_FETCH_RESULT',
    FETCH_ERROR: 'CARD_FETCH_ERROR'
};
export const SET_CARD = 'SET_CARD';
export const SET_GUESS = 'SET_GUESS';
